### ISSUE TITLE
TODO: update latest version with bug fixes to pypi

### ISSUE THREAD

**Issue by jonasfbraun** [NeLy-EPFL/utils2p#12]

**Comment by jasper-tms** [comment]
@sibocw made a nice page on the knowledge base about how to do this: https://github.com/NeLy-EPFL/knowledge-base/wiki/Computation%3A-NeLy-PyPI-account

**Comment by sibocw** [comment]
I did???? It would've been helpful if I remembered this before publishing FlyGym

**Comment by jasper-tms** [comment]
You most certainly did. Seeing that page on the knowledge base got me to start uploading some of my own packages to PyPI ([fanc-fly](https://pypi.org/project/fanc-fly/), [numpyimage](https://pypi.org/project/numpyimage/), [transformix](https://pypi.org/project/transformix/)), and I even made my own (slightly updated) [version of your instructions](https://github.com/jasper-tms/knowledge-base/wiki/Build-a-python-package-and-upload-it-to-PyPI) for my own purposes, so I'm certainly grateful you did.

Anyway, since you're the only one with the credentials for the NeLy PyPI account, we probably need your help to update utils2p. Would you have time to help with this sometime?

**Comment by jasper-tms** [comment]
The nely shared credentials that Sibo gave me were rejected, so I'd guess that @faymanns is the one whose credentials allow uploads to https://pypi.org/project/utils2p/ (and the test server equivalent https://test.pypi.org/project/utils2p/ which is actually the only one I've tried so far). Florian does that sound right to you? If so, do you know how to transfer ownership of `utils2p` on PyPI to the account `nely-epfl` so we can upload new versions?

**Comment by sibocw** [comment]
If you (Florian) click the "Manage Project" button on https://pypi.org/project/utils2p/, under "Collaborators," you should be able to add the account `nely-epfl` as an owner.

**Comment by faymanns** [comment]
Yes, I am indeed the owner. I added `nely-epfl`. You should have received an invite.

**Comment by jasper-tms** [comment]
Thanks Florian. Could you also give us permissions on test.pypi.org?

I went ahead and uploaded to the main pypi.org, so https://pypi.org/project/utils2p/ now shows utils2p as v1.0.0. I hope folks don't mind that I bumped the version up to that from 0.1.0 – seems like this isn't particularly actively developed but is somewhat actively used so might as well promote ourselves from 0.x.x.

One note about something that went wrong during build: I ran `python setup.py sdist bdist_wheel` to prepare the source code and a wheel, but it gave me a wheel with filename `utils2p-1.0.0-cp310-cp310-linux_x86_64.whl` which PyPI wouldn't accept due to this error:
```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Binary wheel 'utils2p-1.0.0-cp310-cp310-linux_x86_64.whl' has an       
         unsupported platform tag 'linux_x86_64'.
```
with some help from GPT I figured out that I can just rename the wheel to have the proper tag, so I did this:
```
mv utils2p-1.0.0-cp310-cp310-linux_x86_64.whl utils2p-1.0.0-cp310-cp310-manylinux_2_17_x86_64.whl
```
and then I was able to upload:
```
cd ~/repos/nely/utils2p
twine upload dist/*
```

I don't know why the build command gave me a wheel with a filename that PyPI rejected – all my packages are updated, so this is quite surprising. Presumably there's a better way to have fixed this problem than renaming the wheel, but whatever, that'll be a problem for another day. Sibo do you know?

If someone (@jonasfbraun?) wouldn't mind installing `utils2p` v1.0.0 from PyPI and testing that it behaves as expected (including the bug fixes that you expect), that would be much appreciated. Then we can close this issue.

**Comment by jasper-tms** [comment]
Note that currently I only have a wheel built for python3.10 on Linux: https://pypi.org/project/utils2p/#files
In principle we could prebuild wheels for other combinations of python versions and operating systems, but my understanding is that this isn't so important for a simple package like utils2p – when users on other systems / python versions run `pip install utils2p`, their computer would download the source code from PyPI and will build the package itself, which is fairly fast again since the package is small. I just tested this on my Macbook / python3.10 and I was able to install utils2p v1.0.0 no problem.

**Comment by jasper-tms** [comment]
Thanks, `nely-epfl` accepted the invite through `test.pypi.org`.

I don't think automatic package publishing is necessarily worth setting up for utils2p because not much development is happening here, but I've been interested in learning how to set up automatic publishing via github actions for other packages. If you want to set it up or explain to me how to do it for utils2p as an example so I can see how it works, I'd certainly be grateful. But I don't know how much work it involves – if it's not a quick thing to set up, I can just google/chatgpt it myself when I want to set it up on a project that's more actively developed.

**Comment by sibocw** [comment]
You can also look at my configs for FlyGym [here](https://github.com/NeLy-EPFL/flygym/tree/main/.github/workflows). I don't have an action set up for publishing to PyPI (I want some manual control over this), but I do have automated style check, unit tests (on all supported Python versions), and docs website build and deployment.

This official [repo](https://github.com/pypa/gh-action-pypi-publish) by PyPA explains how to automate PyPI release if that's something that you would like to do.
